version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/project.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  data_collector:
    level: INFO
    handlers: [console, file]
    propagate: no

  data_processor:
    level: INFO
    handlers: [console, file]
    propagate: no

  analysis:
    level: INFO
    handlers: [console, file, error_file]
    propagate: no

  visualization:
    level: INFO
    handlers: [console, file]
    propagate: no

  api:
    level: INFO
    handlers: [console, file, error_file]
    propagate: no

root:
  level: INFO
  handlers: [console, file, error_file] 