# Configuración general del proyecto
project:
  name: "Análisis Turístico con IA"
  version: "1.0.0"
  environment: "development"

# Configuración de la demostración
demo:
  title: "Demostración de IA en Turismo"
  duration: 120  # minutos
  sections:
    - name: "Análisis de Reseñas"
      duration: 30
      tool: "ChatGPT"
      data: "reseñas.csv"
    - name: "Análisis de Tendencias"
      duration: 30
      tool: "Claude"
      data: "tendencias.json"
    - name: "Dashboard Operativo"
      duration: 30
      tool: "DeepSeek"
      data: "metricas.csv"

# Configuración de APIs
apis:
  openai:
    model: "gpt-4"
    temperature: 0.7
    max_tokens: 1000
    timeout: 10

  anthropic:
    model: "claude-3-opus"
    temperature: 0.7
    max_tokens: 1000
    timeout: 10

  deepseek:
    model: "deepseek-chat"
    temperature: 0.7
    max_tokens: 1000
    timeout: 10

# Configuración de datos
data:
  demo:
    path: "demo/data"
    files:
      reseñas: "reseñas.csv"
      metricas: "metricas.csv"
      tendencias: "tendencias.json"

# Configuración de análisis
analysis:
  reseñas:
    aspects: ["servicio", "instalaciones", "limpieza", "ubicación"]
    min_length: 10
    max_length: 500

  tendencias:
    metrics: ["crecimiento", "estacionalidad", "competencia"]
    periods: ["mensual", "trimestral"]

  dashboard:
    refresh_rate: 60
    metrics: ["ocupacion", "ingresos", "satisfaccion"]
    alerts:
      threshold: 0.8

# Configuración de visualización
visualization:
  theme: "light"
  charts:
    - type: "line"
      name: "Tendencias"
    - type: "bar"
      name: "Métricas"
    - type: "pie"
      name: "Distribución"
    - type: "heatmap"
      name: "Correlaciones"

# Configuración de logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/project.log"
  max_size: 10485760
  backup_count: 5

# Configuración de base de datos
database:
  type: "mongodb"
  host: "localhost"
  port: 27017
  name: "turismo_ia"
  collections:
    - "reseñas"
    - "ventas"
    - "operaciones"
    - "análisis"
    - "reportes"

# Configuración de seguridad
security:
  api_keys:
    path: ".env"
    required:
      - "OPENAI_API_KEY"
      - "ANTHROPIC_API_KEY"
      - "DEEPSEEK_API_KEY"
  data:
    encryption: true
    backup:
      frequency: "daily"
      retention: 30 